exports.Property = function (prop_id,user_id,
    price= undefined,
    surface= undefined,
    levels= undefined,
    level= undefined,
    kitchen= undefined,
    bathroom= undefined,
    living_room= undefined,
    heating= undefined,
    constr_year= undefined,
    available= undefined,
    desc= undefined,
    location= undefined,
    type= undefined) {
        this.prop_id = prop_id
        this.price = price
        this.surface = surface
        this.levels = levels
        this.level = level
        this.kitchen = kitchen
        this.bathroom = bathroom
        this.living_room = living_room
        this.heating = heating
        this.constr_year = constr_year
        this.available = available
        this.desc = desc
        this.location = location
        this.user_id = user_id
        this.type = type
}